spring:
  application:
    name: config-server
  profiles:
    active: docker
  cloud:
    config:
          server:
            git:
              uri: https://github.com/youceyf11/Phd-Tracking-Portal-config-repo.git
              search-paths: config-repo
              default-label: main

server:
  port: 8888


management:
  endpoints:
    web:
      exposure:
        include: health,info
    health:
      show-details: always
