spring:
  application:
    name: eureka-server
  config:
    import: configserver:http://config-server:8888/
  cloud:
    config:
      fail-fast: false
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: eureka-server
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 10000
    renewal-percent-threshold: 0.85

management:
  endpoints:
    web:
      exposure:
        include: "*"