server:
  port: 8082

spring:
  application:
    name: inscription-service
  cloud:
    config:
      import: configserver:http://config-server:8888/
      fail-fast: true
      retry:
        max-attempts: 10
        initial-interval: 2000
        multiplier: 1.5
  datasource:
    url: jdbc:postgresql://postgres:5432/inscription_db
    username: postgres
    password: postgres

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    hostname: user-service
    prefer-ip-address: false

logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    org.springframework.boot: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000
