server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://postgres:5432/phd_tracking
    username: postgres
    password: postgres
  kafka:
    bootstrap-servers: kafka:29092

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    org.springframework.boot: DEBUG
  org.springframework.boot.actuate: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always
  security:
    enabled: false

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000


