spring:
  application:
    name: user-service
  cloud:
    config:
      uri: http://config-server:8888
      fail-fast: true
      retry:
        max-attempts: 10
        initial-interval: 2000
        multiplier: 1.5
  datasource:
    url: jdbc:postgresql://postgres:5432/phd_tracking
    username: postgres
    password: postgres

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    hostname: user-service
    prefer-ip-address: false


management:
  endpoints:
    web:
      exposure:
        include: "*"
