spring:
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    root: DEBUG